theme = "autumn_night"

[editor]
line-number = "relative"
mouse = false
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]
cursorline = true


# [editor.lsp]
# enable = true
# display-messages = true
# display-inlay-hints = true
# snippets = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"


[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[keys.normal]
C-s = ":w"
C-q = ":q!"
C-z = ":wq!"



