theme = "personal_theme"

[editor]
line-number = "relative"
mouse = false
cursorline = true
shell = ["zsh", "-ic"]
popup-border = "all"

[editor.lsp]
enable = true
display-messages = true
snippets = true
display-progress-messages = true
display-signature-help-docs = true
goto-reference-include-declaration = true
display-color-swatches = true


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = [
  "spinner",
  "mode",
  "file-name",
  "read-only-indicator",
  "file-modification-indicator",
]
center = ["version-control"]
right = ["diagnostics", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]


[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[editor.indent-guides]
render = true
character = "╎"
skip-levels = 1

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.soft-wrap]
enable = true
max-wrap = 25
max-indent-retain = 0
wrap-indicator = ""

[keys.normal]
C-s = ":write"
C-z = ":quit!"
C-q = ":write-quit"
C-o = ":o ~/.config/helix/config.toml"
C-l = ":o ~/.config/helix/languages.toml"
