#powershell
[language-server.powershell-editor-services]
command = "pwsh"
args = [
  "-NoLogo",
  "-NoProfile",
  "-Command",
  "/home/suvan/main/system-tools/PowerShellEditorServices/PowerShellEditorServices/Start-EditorServices.ps1 -SessionDetailsPath ./session.json  -FeatureFlags @() -AdditionalModules @() -HostName helix -HostProfileId 0 -HostVersion 1.0.0 -Stdio -LogLevel Normal",
]
config = {}

[[language]]
name = "powershell"
indent = { tab-width = 2, unit = "  " }
auto-format = true
language-servers = ["powershell-editor-services"]
#powershell end


#javascript-typescript
[language-server.biome]
command = "biome"
args = ["lsp-proxy"]

[language-server.tsgo]
command = "tsgo"
args = ["--lsp", "--stdio"]

[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]

# [[language]]
# name = "javascript"
# roots = ["biome.json", "jsconfig.json"]
# auto-format = true
# indent = { tab-width = 2, unit = "  " }
# language-servers = [
#   { name = "typescript-language-server", except-features = [
#     "signature-help",
#     "inlay-hints",
#     "format",
#   ] },
#   "biome",
# ]

[[language]]
name = "typescript"
roots = ["tsconfig.json"]
auto-format = true
language-servers = [
  { name = "tsgo", except-features = [
    "signature-help",
    "inlay-hints",
    "format",
  ] },
  # { name = "typescript-language-server", except-features = [
  #   "signature-help",
  #   "inlay-hints",
  #   "format",
  # ] },
  "biome",
]
#javascript-typescript end

#json
[[language]]
name = "json"
language-servers = [
  { name = "vscode-json-language-server", except-features = [
    "format",
  ] },
  "biome",
]
#json end

#json
[[language]]
name = "jsonc"
language-servers = [
  { name = "vscode-json-language-server", except-features = [
    "format",
  ] },
  "biome",
]
#json end

[language-server.tailwindcss-language-server]
command = "tailwindcss-language-server"
args = ["--stdio"]
config = {}

#jsx
[[language]]
name = "jsx"
roots = ["jsconfig.json"]
auto-format = true
language-servers = [
  { name = "tsgo", except-features = [
    "signature-help",
    "inlay-hints",
    "format",
  ] },
  { name = "typescript-language-server", except-features = [
    "signature-help",
    "inlay-hints",
    "format",
  ] },
  "tailwindcss-language-server",
  "biome",
]
#jsx end


#tsx
[[language]]
name = "tsx"
roots = ["tsconfig.json"]
auto-format = true
language-servers = [
  { name = "tsgo", except-features = [
    "signature-help",
    "inlay-hints",
    "format",
  ] },
  { name = "typescript-language-server", except-features = [
    "signature-help",
    "inlay-hints",
    "format",
  ] },
  "biome",
]
#tsx end

#css
[[language]]
name = "css"
auto-format = true
language-servers = [
  # "tailwindcss-language-server"
  "vscode-css-language-server",
]
#css end


#html
[language-server.vscode-html-language-server]
command = "vscode-html-language-server"

[[language]]
name = "html"
auto-format = true
# roots = ["angular.json"]
language-servers = ["vscode-html-language-server"]
#html end

#markdown
[language-server.markdown-oxide]
command = "markdown-oxide"

[[language]]
name = "markdown"
auto-format = true
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"] }
language-servers = ["markdown-oxide"]
#markdown end

#toml
[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true
language-servers = ["taplo"]
#toml end

#yaml
[language-server.yaml-language-server]
command = "yaml-language-server"
args = ["--stdio"]

[[language]]
name = "yaml"
auto-format = true
language-servers = ["yaml-language-server"]
#yaml


#dockerfile
[language-server.docker-langserver]
command = "docker-langserver"

[[language]]
name = "dockerfile"
auto-format = true
language-servers = ["docker-langserver"]
#dockerfile


#yaml
[[language]]
name = "docker-compose"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "yaml"] }
language-servers = ["yaml-language-server"]
#yaml

#astro
[language-server.astro-ls]
command = "astro-ls"
args = ["--stdio"]
config = { "typescript" = { "tsdk" = "C:/Users/HP/.bun/install/global/node_modules/typescript/lib/" }, enviroment = "node" }

[[language]]
name = "astro"
roots = ["package.json", "astro.config.mjs", "astro.config.ts"]
auto-format = true
language-servers = ["astro-ls", "tsgo", "typescript-language-server", "biome"]
#astro end
