#python
[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.ruff]
command = "ruff"
args = ["server"]
environment = { "RUFF_TRACE" = "messages" }

[language-server.ruff.config.settings]
lineLength = 80
logLevel = "debug"

[language-server.ruff.config.settings.lint]
select = [
  "E",
  "F",
  "W",
  "B",
  "I",
  "RUF",
  "N",
  "LOG",
  "ERA",
  "W",
  "D",
  "UP",
  "ANN",
  "ASYNC",
  "S",
  "RET",
  "TCH",
  "ARG",
  "PTH",
  "DOC",
]
preview = true

[language-server.ruff.config.settings.format]
preview = true
quote-style = "double"
docstring-code-format = true
indent-style = "space"

[[language]]
name = "python"
language-id = "python"
roots = ["pyproject.toml", "setup.py", "poetry.lock", ".git", ".jj", ".venv/"]
language-servers = ["ruff", "pyright"]
auto-format = true
formatter = { command = "ruff", args = ["format", "-"] }
file-types = ["py", "ipynb"]
comment-token = "#"
shebangs = ["python"]
#python

#bash
[language-server.bash-lsp]
command = "bash-language-server"
args = ["start"]

[[language]]
name = "bash"
scope = "source.sh"
indent = { tab-width = 2, unit = "  " }
auto-format = true
language-servers = ["bash-lsp"]
#bash end

#powershell
# [language-server.powershell-editor-services-lsp]
# command = "bash-language-server"
# args = ["start"]

[[language]]
name = "powershell"
scope = "source.ps1"
indent = { tab-width = 2, unit = "  " }
# auto-format = true
# language-servers = ["bash-lsp"]
#powershell

#javascript-typescript
[language-server.biome]
command = "biome"
args = ["lsp-proxy"]


[[language]]
name = "javascript"
scope = "source.js"
file-types = ["cjs", "js", "mjs"]
auto-format = true
indent = { tab-width = 2, unit = "  " }
language-servers = [
  { name = "typescript-language-server", only-features = [
    "goto-definition",
    "goto-declaration",
    "goto-type-definition",
    "goto-reference",
    "goto-implementation",
    "document-highlight",
    "workspace-command",
    "document-symbols",
    "workspace-symbols",
    "rename-symbol",
    "diagnostics",
    "completion",
  ] },
  "tailwindcss-language-server",
  "biome",
]


[[language]]
name = "typescript"
scope = "source.ts"
file-types = ["ts"]
auto-format = true
indent = { tab-width = 2, unit = "  " }
language-servers = [
  { name = "typescript-language-server", only-features = [
    "goto-definition",
    "goto-declaration",
    "goto-type-definition",
    "goto-reference",
    "goto-implementation",
    "document-highlight",
    "workspace-command",
    "document-symbols",
    "workspace-symbols",
    "rename-symbol",
    "diagnostics",
    "completion",
  ] },
  "tailwindcss-language-server",
  "biome",
]
#javascript-typescript end

#json
[[language]]
name = "json"
scope = "source.json"
file-types = ["json"]
language-servers = [
  { name = "vscode-json-language-server", except-features = [
    "format",
  ] },
  "biome",
]
#json end

[language-server.tailwindcss-language-server]
command = "tailwindcss-language-server"
args = ["--stdio"]
config = {}

#jsx
[[language]]

name = "jsx"
scope = "source.jsx"
file-types = ["jsx"]

indent = { tab-width = 4, unit = "\t" }
auto-format = true
language-servers = [
  { name = "typescript-language-server", only-features = [
    "goto-definition",
    "goto-declaration",
    "goto-type-definition",
    "goto-reference",
    "goto-implementation",
    "document-highlight",
    "workspace-command",
    "document-symbols",
    "workspace-symbols",
    "rename-symbol",
    "diagnostics",
    "completion",
  ] },
  "tailwindcss-language-server",
  "biome",
]
#jsx end


#tsx
[[language]]

name = "tsx"
scope = "source.tsx"
file-types = ["tsx"]

indent = { tab-width = 4, unit = "\t" }
auto-format = true
language-servers = [
  { name = "typescript-language-server", only-features = [
    "goto-definition",
    "goto-declaration",
    "goto-type-definition",
    "goto-reference",
    "goto-implementation",
    "document-highlight",
    "workspace-command",
    "document-symbols",
    "workspace-symbols",
    "rename-symbol",
    "diagnostics",
    "completion",
  ] },
  "tailwindcss-language-server",
  "biome",
]
#tsx end

#css
[[language]]
name = "css"
scope = "source.css"
file-types = ["css"]
auto-format = true
language-servers = ["tailwindcss-language-server", "vscode-css-language-server"]
#css end


#html
[[language]]
name = "html"
language-servers = [
  "vscode-html-language-server",
  "tailwindcss-language-server",
]
#html end

#markdown
[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]
config = {}

[[language]]
name = "markdown"
scope = "source.md"
file-types = ["md"]
auto-format = true
formatter = { command = "mdformat", args = ["-"] }
language-servers = ["harper-ls"]
#markdown end

#toml
[[language]]
name = "toml"
scope = "source.toml"
file-types = ["toml"]
indent = { tab-width = 2, unit = "  " }
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true
language-servers = ["taplo"]
#toml end

#go
[language-server.golangci-lint-langserver]
command = "golangci-lint-langserver"

[language-server.golangci-lint-langserver.config]
command = [
  "golangci-lint",
  "run",
  "--out-format",
  "json",
  "--issues-exit-code=1",
]

[[language]]
name = "go"
scope = "source.go"
file-types = ["go"]
auto-format = true
indent = { tab-width = 2, unit = "  " }
formatter = { command = "gofmt" }
language-servers = [
  { name = "gopls", only-features = [
    "goto-definition",
    "goto-declaration",
    "goto-type-definition",
    "goto-reference",
    "goto-implementation",
    "document-highlight",
    "workspace-command",
    "document-symbols",
    "workspace-symbols",
    "rename-symbol",
    "diagnostics",
    "completion",
  ] },
  "golangci-lint-langserver",
]
#go end

#vue 
[[language-server.typescript-language-server.config.plugins]]
name = "@vue/typescript-plugin"
location = "D:/.bun/install/global/node_modules/@vue/language-server"
languages = ["vue"]

[[language]]
name = "vue"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "vue"] }
language-servers = ["typescript-language-server"]
#vue end
