#python
[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.ruff]
command = "ruff"
args = ["server"]
environment = { "RUFF_TRACE" = "messages" }

[language-server.ruff.config.settings]
lineLength = 80
logLevel = "debug"

[language-server.ruff.config.settings.lint]
select = [
  "E",
  "F",
  "W",
  "B",
  "I",
  "RUF",
  "N",
  "LOG",
  "ERA",
  "W",
  "D",
  "UP",
  "ANN",
  "ASYNC",
  "S",
  "RET",
  "TCH",
  "ARG",
  "PTH",
  "DOC",
]
preview = true

[language-server.ruff.config.settings.format]
preview = true
quote-style = "double"
docstring-code-format = true
indent-style = "space"

[[language]]
name = "python"
roots = ["pyproject.toml", "setup.py", "poetry.lock", ".git", ".jj", ".venv/"]
language-servers = ["ruff", "pyright"]
auto-format = true
formatter = { command = "ruff", args = ["format", "-"] }
file-types = ["py", "ipynb"]
comment-token = "#"
shebangs = ["python"]
#python

#bash
[language-server.bash-language-server]
command = "bash-language-server"
args = ["start"]

[[language]]
name = "bash"
indent = { tab-width = 2, unit = "  " }
auto-format = true
language-servers = ["bash-language-server"]
#bash end

#powershell
# [language-server.powershell-editor-services-lsp]
# command = "bash-language-server"
# args = ["start"]

[[language]]
name = "powershell"
scope = "source.ps1"
indent = { tab-width = 2, unit = "  " }
# auto-format = true
# language-servers = ["bash-lsp"]
#powershell

#javascript-typescript
[language-server.biome]
command = "biome"
args = ["lsp-proxy"]


[[language]]
name = "javascript"
roots = ["biome.json", "jsconfig.json"]
file-types = ["cjs", "js", "mjs"]
auto-format = true
indent = { tab-width = 2, unit = "  " }
language-servers = [
  { name = "typescript-language-server", except-features = [
    "signature-help",
    "inlay-hints",
    "format",
  ] },
  "tailwindcss-language-server",
  "biome",
]


[[language]]
name = "typescript"
roots = [
  "biome.json",
  "tsconfig.json",
  "tsconfig.base.json",
  "tsconfig.client.json",
  "tsconfig.app.json",
  "tsconfig.server.json",
  "tsconfig.node.json",
]
file-types = ["ts", "mts"]
auto-format = true
indent = { tab-width = 2, unit = "  " }
language-servers = [
  { name = "typescript-language-server", except-features = [
    "signature-help",
    "inlay-hints",
    "format",
  ] },
  "tailwindcss-language-server",
  "biome",
]
#javascript-typescript end

#json
[[language]]
name = "json"
language-servers = [
  { name = "vscode-json-language-server", except-features = [
    "format",
  ] },
  "biome",
]
#json end

[language-server.tailwindcss-language-server]
command = "tailwindcss-language-server"
args = ["--stdio"]
config = {}

#jsx
[[language]]
name = "jsx"
roots = ["biome.json", "tsconfig.json"]
indent = { tab-width = 4, unit = "\t" }
auto-format = true
language-servers = [
  { name = "typescript-language-server", except-features = [
    "signature-help",
    "inlay-hints",
    "format",
  ] },
  "tailwindcss-language-server",
  "biome",
]
#jsx end


#tsx
[[language]]
name = "tsx"
roots = ["biome.json", "tsconfig.json"]
indent = { tab-width = 4, unit = "\t" }
auto-format = true
language-servers = [
  { name = "typescript-language-server", except-features = [
    "signature-help",
    "inlay-hints",
    "format",
  ] },
  "tailwindcss-language-server",
  "biome",
]
#tsx end

#css
[[language]]
name = "css"
auto-format = true
language-servers = ["tailwindcss-language-server", "vscode-css-language-server"]
#css end


#html
[[language]]
name = "html"
language-servers = [
  "vscode-html-language-server",
  "tailwindcss-language-server",
]
#html end

#markdown
[language-server.markdown-oxide]
command = "markdown-oxide"

[[language]]
name = "markdown"
auto-format = true
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"] }
language-servers = ["markdown-oxide"]
#markdown end

#toml
[[language]]
name = "toml"
indent = { tab-width = 2, unit = "\t" }
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true
language-servers = ["taplo"]
#toml end

#go
[language-server.golangci-lint-langserver]
command = "golangci-lint-langserver"

[language-server.golangci-lint-langserver.config]
command = [
  "golangci-lint",
  "run",
  "--out-format",
  "json",
  "--issues-exit-code=1",
]

[[language]]
name = "go"
auto-format = true
indent = { tab-width = 2, unit = "\t" }
formatter = { command = "gofmt" }
language-servers = [
  { name = "gopls", except-features = [
    "signature-help",
    "inlay-hints",
  ] },
  "golangci-lint-langserver",
]
#go end

#vue 
[[language-server.typescript-language-server.config.plugins]]
name = "@vue/typescript-plugin"
location = "/home/suvan/.bun/install/global/node_modules/@vue/language-server"
languages = ["vue"]

[[language]]
name = "vue"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "vue"] }
language-servers = ["typescript-language-server"]
#vue end

#java
[language-server.jdtls]
command = "jdtls"
location = "~/main/system-tools/jdtls/bin"

[[language]]
name = "java"
roots = ["pom.xml"]
auto-format = true
indent = { tab-width = 2, unit = "\t" }
language-servers = [
  { name = "jdtls", except-features = [
    "signature-help",
    "inlay-hints",
  ] },
]
#java end


#dart
[language-server.dart]
command = "dart"

[[language]]
name = "dart"
auto-format = true
indent = { tab-width = 2, unit = "\t" }
formatter = { command = "dart", args = ["format"] }
language-servers = [
  { name = "dart", except-features = [
    "signature-help",
    "inlay-hints",
  ] },
]
#dart end

#cpp 
[language-server.clangd]
command = "clangd"
args = ["--background-index", "--compile-commands-dir=./build", "--clang-tidy"]

[[language]]
name = "cpp"
file-types = ["cpp", "hpp", "cc", "hh"]
auto-format = true
indent = { tab-width = 2, unit = "\t" }
language-servers = [
  { name = "clangd", except-features = [
    "signature-help",
    "inlay-hints",
  ] },
]
#cpp end


#rust
[language-server.rust-analyzer]
command = "rust-analyzer"

[[language]]
name = "rust"
auto-format = true
indent = { tab-width = 2, unit = "\t" }
language-servers = [
  { name = "rust-analyzer", except-features = [
    "signature-help",
    "inlay-hints",
  ] },
]
#rust end


#ruby
[language-server.solargraph]
command = "solargraph"
args = ["stdio"]
config = { diagnostics = false, formatting = false }

[language-server.rubocop]
command = "rubocop"
args = ["--lsp", "--stderr", "--fail-level", "fatal"]
timeout = 3

[[language]]
name = "ruby"
auto-format = true
indent = { tab-width = 2, unit = "\t" }
language-servers = [
  { name = "solargraph", except-features = [
    "signature-help",
    "inlay-hints",
    "diagnostics",
    "format",
  ] },
  "rubocop",
]
#ruby end

#csharp
[language-server.omnisharp]
command = "/home/suvan/main/system-tools/omnisharp-roslyn/omnisharp/OmniSharp.exe"
args = ["-lsp"]
timeout = 10000

[[language]]
name = "c-sharp"
roots = ["sln", "csproj"]
auto-format = true
indent = { tab-width = 2, unit = "\t" }
language-servers = [
  { name = "omnisharp", except-features = [
    "signature-help",
    "inlay-hints",
  ] },
]
#csharp end
