# author: suvanshenoy

"ui.background" = {}
"ui.background.separator" = { fg = "white", modifiers = ["bold"] }

# "ui.cursor" = { fg = "#525252", modifiers = ["reversed", "dim"] }
"ui.cursor.match" = { fg = "light-gray", modifiers = ["reversed"] }
"ui.cursor.primary" = { fg = "gray", modifiers = ["reversed"] }
"ui.cursor.secondary" = { fg = "white", modifiers = ["reversed"] }

"ui.gutter" = {}
"ui.gutter.selected" = { bg = "black" }

"ui.help" = { fg = "white", bg = "black" }

"ui.linenr" = { fg = "gray", modifiers = ["bold"] }
"ui.linenr.selected" = { fg = "white", modifiers = ["bold"] }

"ui.menu" = { bg = "black", fg = "light-gray", modifiers = ["dim"] }

"ui.menu.selected" = { fg = "gray", modifiers = ["reversed", "dim"] }
"ui.menu.scroll" = { fg = "gray", modifiers = ["dim"] }

"ui.popup" = { bg = "black", fg = "light-gray", modifiers = ["dim"] }

"ui.selection" = { bg = "gray" }

"ui.statusline" = { bg = "black" }
"ui.statusline.inactive" = { bg = "black" }
"ui.statusline.separator" = { fg = "light-blue", bg = "blue", modifiers = [
  "bold",
] }

"ui.virtual" = { bg = "black" }
"ui.virtual.indent-guide" = { fg = "gray" }
"ui.virtual.whitespace" = {}
"ui.virtual.wrap" = { fg = "gray" }
"ui.virtual.inlay-hint" = { fg = "light-gray", modifiers = ["dim", "italic"] }
"ui.virtual.inlay-hint.parameter" = { fg = "yellow", modifiers = [
  "dim",
  "italic",
] }
"ui.virtual.inlay-hint.type" = { fg = "blue", modifiers = ["dim", "italic"] }

"ui.window" = { bg = "black", fg = "gray", modifiers = ["dim"] }


"comment" = { fg = "light-green", modifiers = ["italic", "dim"] }
"comment.block.documentation" = { fg = "red" }
"comment.line.documentation" = { fg = "blue" }


"attribute" = { fg = "green" }
"constant" = { fg = "light-blue", modifiers = ["dim"] }
"constant.numeric" = { fg = "light-blue", modifiers = ["dim"] }
"constant.character.escape" = "light-cyan"
"constructor" = { fg = "green", modifiers = ["dim"] }
"function" = { fg = "light-magenta", modifiers = ["dim"] }
"function.macro" = { fg = "light-red", modifiers = ["dim"] }
"tag" = { fg = "#fffff7", modifiers = ["dim"] }
"type" = { fg = "light-magenta", modifiers = ["dim"] }
"type.builtin" = { fg = "light-red", modifiers = ["dim"] }
"type.enum.variant" = { fg = "green" }
"string" = { fg = "light-blue", modifiers = ["dim"] }
"special" = { fg = "light-red", modifiers = ["dim"] }
"variable" = { fg = "#ffb347", modifiers = ["dim"] }
"variable.parameter" = { fg = "#ffb347", modifiers = ["dim", "italic"] }
"variable.other.member" = { fg = "#ffb347", modifiers = ["dim"] }
"keyword" = { fg = "light-red", modifiers = ["dim"] }
"keyword.control.exception" = { fg = "light-red", modifiers = ["dim"] }
"keyword.directive" = { fg = "light-red", modifiers = ["dim"] }
"keyword.operator" = { fg = "green", modifiers = ["dim"] }
"label" = { fg = "light-blue", modifiers = ["dim"] }
"namespace" = { fg = "green", modifiers = ["dim"] }

"markup.heading" = { fg = "blue", modifiers = ["dim"] }
"markup.list" = { fg = "light-red" }
"markup.bold" = { modifiers = ["dim"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "light-magenta", modifiers = ["underlined"] }
"markup.link.text" = { fg = "blue", modifiers = ["italic"] }
"markup.quote" = "light-cyan"
"markup.raw" = "light-green"

"diff.plus" = "light-green"
"diff.delta" = "light-yellow"
"diff.minus" = "light-red"

"diagnostic.hint" = { underline = { color = "gray", style = "curl" } }
"diagnostic.info" = { underline = { color = "light-cyan", style = "curl" } }
"diagnostic.warning" = { underline = { color = "light-yellow", style = "curl" } }
"diagnostic.error" = { underline = { color = "light-red", style = "curl" } }

"info" = { fg = "light-cyan" }
"hint" = { fg = "light-gray" }
"debug" = { fg = "white" }
"warning" = { fg = "yellow" }
"error" = { fg = "light-red" }
