# author: suvanshenoy

"ui.background" = { }
"ui.background.separator" = { fg = "red" }
"ui.cursor" = { fg = "light-gray", modifiers = ["reversed"] }
"ui.cursor.match" = { fg = "light-gray", modifiers = ["reversed"] }
"ui.cursor.primary" = { fg = "white", modifiers = ["reversed"] }
"ui.cursor.secondary" = { fg = "gray", modifiers = ["reversed"] }
"ui.cursorline.primary" = { bg = "black" }
"ui.gutter" = {}
"ui.gutter.selected" = { bg = "black" }
"ui.help" = { fg = "white", bg = "black" }
"ui.linenr" = { fg = "gray", modifiers = ["bold"] }
"ui.linenr.selected" = { fg = "white", modifiers = ["bold"] }
"ui.menu" = { fg = "light-gray", bg = "gray" }
"ui.menu.selected" = { modifiers = ["reversed"] }
"ui.menu.scroll" = { fg = "light-blue" }
"ui.popup" = { bg = "black" }
"ui.selection" = { bg = "gray" }
"ui.statusline" = { fg = "light-gray", bg = "gray" }
"ui.statusline.inactive" = { bg = "black" }
"ui.virtual" = { bg = "black" }
"ui.virtual.indent-guide" = { fg = "gray" }
"ui.virtual.whitespace" = {}
"ui.virtual.wrap" = { fg = "gray" }
"ui.virtual.inlay-hint" = { fg = "light-gray", modifiers = ["dim", "italic"] }
"ui.virtual.inlay-hint.parameter" = { fg = "yellow", modifiers = ["dim", "italic"] }
"ui.virtual.inlay-hint.type" = { fg = "blue", modifiers = ["dim", "italic"] }
"ui.window" = { fg = "gray", modifiers = ["dim"] }

"comment" = { fg = "light-gray", modifiers = ["italic", "dim"] }

"attribute" = "light-yellow"
"constant" = { fg = "light-yellow", modifiers = ["bold", "dim"] }
"constant.numeric" = "light-yellow"
"constant.character.escape" = "light-cyan"
"constructor" = "white" # "light-blue"
"function" = { fg = "light-magenta", modifiers=["bold"] }    # "light-blue"
"function.macro" = { fg = "white" , modifiers = ["bold"] } # "light-red"
"function.builtin" = {fg = "white" , modifiers = ["bold"]} # { fg = "light-blue", modifiers =
"tag" = { fg = "white", modifiers = ["bold"]} # { fg = "light-magenta", modifiers = ["dim"] }
"type" = {fg = "white", modifiers =["bold"]}        # "blue"
"type.builtin" = { fg = "white", modifiers=["bold"] }   # { fg = "blue", modifiers = ["bold"]
"type.enum.variant" = "white" # { fg = "light-magenta", modifiers = ["dim"] }
"string"  = "white"   # "light-green"
"special" = "light-red"
"variable" = { fg = "orange", modifiers=["bold"] }
"variable.parameter" =  {fg = "light-white" , modifiers=["italic"]} # { fg = "light-yellow", modifiers = ["italic"] }
"variable.other.member" = "light-green"
"keyword" =  {fg = "light-red", modifiers = ["bold"] } # "light-magenta"
"keyword.control.exception" = "light-red"
"keyword.directive" =  {fg = "white", modifiers = ["bold"]} # { fg = "light-yellow", modifiers = ["bold"] }
"keyword.operator" =  {fg = "white", modifiers = ["bold"]}  # { fg = "light-blue", modifiers = ["bold"] }
"label" = "light-green"
"namespace" = {fg = "white", modifiers=["bold"]} # { fg = "blue", modifiers = ["dim"] }

"markup.heading" = "light-blue"
"markup.list" = "light-red"
"markup.bold" = { fg = "light-cyan", modifiers = ["bold"] }
"markup.italic" = { fg = "light-blue", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "magenta", modifiers = ["dim"] }
"markup.link.text" = "light-magenta"
"markup.quote" = "light-cyan"
"markup.raw" = "light-green"

"diff.plus" = "light-green"
"diff.delta" = "light-yellow"
"diff.minus" = "light-red"

"diagnostic.hint" = { underline = { color = "gray", style = "curl" } }
"diagnostic.info" = { underline = { color = "light-cyan", style = "curl" } }
"diagnostic.warning" = { underline = { color = "light-yellow", style = "curl" } }
"diagnostic.error" = { underline = { color = "light-red", style = "curl" } }

"info" = "light-cyan"
"hint" = { fg = "light-gray", modifiers = ["dim"] }
"debug" = "white"
"warning" = "yellow"
"error" = "light-red"
